{
 "title": "Git-Backed-REST API Dashboard",
 "tags": [
  "git-backed-rest",
  "api",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Status Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (increase(request_count[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Rate by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (increase(request_count[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Average Request Duration by HTTP Verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(request_duration_sum[5m])) / sum by (method) (rate(request_count[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"git-backed-rest\"}[5m]) * 100",
     "legendFormat": "CPU Usage %"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(process_resident_memory_bytes{job=\"git-backed-rest\"} / 1024 / 1024)",
     "legendFormat": "Memory Usage MB"
    },
    {
     "expr": "rate(process_virtual_memory_max_bytes{job=\"git-backed-rest\"}[5m]) / 1024 / 1024",
     "legendFormat": "Max Memory MB"
    }
   ]
  },
  {
   "title": "Request Rate by Result Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(request_count{status=\"success\",retry=\"false\"}[5m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(request_count{status=\"success\",retry=\"true\"}[5m]))",
     "legendFormat": "retried"
    },
    {
     "expr": "sum(rate(request_count{status=\"error\"}[5m]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "HTTP Verb Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (increase(request_count[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}